name: Docker Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: sanjeev91/voice-bot:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull sanjeev91/voice-bot:latest
            sudo docker stop sanjeev91/voice-bot || true
            sudo docker rm sanjeev91/voice-bot || true
            sudo docker run -d --restart always --name sanjeev91/voice-bot --env-file .env -p 8080:8080 sanjeev91/voice-bot:latest
            sudo docker image prune -f